name = "AcousticRayTracers"
uuid = "4fc4fbda-03ee-4929-b565-b3d9b12bdf79"
authors = ["Mandar Chitre <mandar@nus.edu.sg>"]
version = "0.2.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
UnderwaterAcoustics = "0efb1f7a-1ce7-46d2-9f48-546a4c8fbb99"

[compat]
julia = "1.6"
Optim = "1.6 - 1.9"
ForwardDiff = "0.10"
OrdinaryDiffEq = "6.9 - 6.70"
UnderwaterAcoustics = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
